spring:
  application:
    name: todolist-api
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist-api_db
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create